package dev.giona.ktconf.api

import dev.tramai.sovereign.SovereignTramai
import dev.tramai.sovereign.evidence.SovereignEvidencePackV1
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

/**
 * Read-only exposure of TramAI's publish-safe runtime posture.
 *
 * The pack is generated by the one starter-composed SovereignTramai instance;
 * this controller does not create a second runtime or duplicate policy state.
 */
@RestController
@RequestMapping("/governance")
class SovereignEvidenceController(
    private val tramai: SovereignTramai,
) {
    @GetMapping("/sovereign-evidence")
    fun evidence(): SovereignEvidencePackV1 = tramai.evidencePack()
}
